language: node_js
node_js: 
  - 13

services:
  - docker 

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script: 
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed 014091804/udagram-api-feed

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user 014091804/udagram-api-user

  - docker build -t udagram-frontend:latest ./udagram-frontend
  - docker tag udagram-frontend 014091804/udagram-frontend:v1

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy 014091804/reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 014091804/udagram-api-feed
  - docker push 014091804/udagram-api-user
  - docker push 014091804/udagram-frontend
  - docker push 014091804/reverseproxy