apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-user
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - image: 014091804/udagram-api-user
        name: api-user
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: udagram-067328141418-env
          - secretRef:
              name: udagram-db-secret
          - secretRef:
              name: aws-cre 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"                   
        volumeMounts:
        - name: aws-cre
          mountPath: "/root/.aws/"
          readOnly: true        
      volumes:
      - name: aws-cre
        secret:
          secretName: aws-cre      