apiVersion: v1
kind: Secret
metadata:
  name: aws-cre
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVE3TElSNUJWTEpSN0tJSEYKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gNHpEdk43NURsZGRGdXJBSjdBYnczcmk4Y1Jyd0czQTYybkNhaXlDQwogICAgCg==
